#ifndef GSH_HISTORY_PROTOCOL_H
#define GSH_HISTORY_PROTOCOL_H

#include <stdint.h>

enum {
    GSH_HISTORY_PROTOCOL_MAGIC = 0x47534848U,
    GSH_HISTORY_PROTOCOL_VERSION = 1,
    GSH_HISTORY_MESSAGE_STATUS = 1,
    GSH_HISTORY_MESSAGE_UNLOCK = 2,
    GSH_HISTORY_MESSAGE_RESET = 3,
    GSH_HISTORY_MESSAGE_ADD = 4,
    GSH_HISTORY_MESSAGE_VERIFY = 5,
    GSH_HISTORY_MESSAGE_LOCK = 6,
    GSH_HISTORY_MESSAGE_RESPONSE = 7,
    GSH_HISTORY_MESSAGE_SHUTDOWN = 8,
    GSH_HISTORY_STATUS_OK = 0,
    GSH_HISTORY_STATUS_LOCKED = 1,
    GSH_HISTORY_STATUS_NEW = 2,
};

typedef struct {
    uint32_t magic;
    uint32_t version;
    uint32_t type;
    uint32_t length;
    int32_t status;
} gsh_history_message;

#endif
